-- SQLite table matching data/processed/water_park_daily_analysis.csv.
DROP TABLE IF EXISTS water_park_daily_analysis;
CREATE TABLE water_park_daily_analysis (
    date TEXT PRIMARY KEY,
    admission_revenue REAL NOT NULL,
    is_weekday INTEGER NOT NULL,
    is_holiday INTEGER NOT NULL,
    receipt_rows INTEGER NOT NULL,
    distinct_receipts INTEGER NOT NULL,
    first_receipt_hour INTEGER,
    last_receipt_hour INTEGER,
    actual_tickets INTEGER NOT NULL CHECK (actual_tickets >= 0),
    temperature_high REAL,
    temperature_low REAL,
    average_temperature REAL,
    precipitation REAL,
    precipitation_reported INTEGER,
    weather_condition TEXT,
    wind_speed REAL,
    humidity REAL,
    weather_hour_count INTEGER,
    year INTEGER NOT NULL,
    month_number INTEGER NOT NULL,
    month_name TEXT NOT NULL,
    week_of_year INTEGER NOT NULL,
    day_of_month INTEGER NOT NULL,
    day_of_week TEXT NOT NULL,
    day_of_week_number INTEGER NOT NULL,
    is_weekend INTEGER NOT NULL,
    season TEXT NOT NULL,
    days_since_season_open INTEGER NOT NULL,
    days_until_season_close INTEGER NOT NULL,
    precipitation_indicator INTEGER,
    temperature_band TEXT,
    seven_day_rolling_average REAL,
    prior_operating_day_attendance REAL,
    attendance_change_from_prior_day REAL,
    attendance_percent_change_from_prior_day REAL,
    attendance_category TEXT NOT NULL,
    operating_status TEXT
);
